development:
  adapter: postgresql
  database: development
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password:
  host: db

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: production
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password:
  host: db
